version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.444.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.449.0
    - 1.452.0
    - 1.488.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
  - dependency-name: type-coverage
    versions:
    - 2.17.1
  - dependency-name: cross-fetch
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: css-loader
    versions:
    - 5.1.3
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
