language: clojure
dist: bionic
env:
  - secure: ny/iTI7GRnhh9XjdYyGbC8LqNowdX/KQKXKYiD0xXm/rJnnjB1a5TUZlWx3dTOkL8cQ5DKuCrYcV8roJTYdMvW+Dg7bDBV81jd9oJxkupSxU5ij6wGhNjKa02p6bGqeMur5/Ml8sAW633Ed8u8j8chkVUOyOh9U27dGE2E2B5idP1t8JxcrWuO4wxQTV1EKDRXLrYN6paASgbzIgrRRnsMEpGmN2hnOe7jz0EKOToA4FH7JWwhhPyvwUjslCbeTA8gwizL8/3FQvQYIYtwBBA0+HF4RB/ZCgsUs7o1t5RLQPAa5I1eqB7o3oNQ6r+dvdfFnjKTlC7vLQ2lq5XoIWd3mJoNh8xEej20xd3HoX7U5AvrjJADs2rfYMLt0XqhUqRtsGwp2FhWa8k8NqK43Qhn+w4glwRerkY1MAkh+xyqYUrs/GQHTwRurClWjIa4DvGtRwUYJMoMgdbJ46j82nk0JmnWAlc0motQmrAsnM4ED4BGL6Nm9cTkdmGS2aeH8OsPkjRP88kn675VzvceLTJW6dCnRY2UOWiEZJZ5rru38d24gpSoIKi/APoC65zOAofekHvvczYXIg4nq9YwNeYFKaIq8CZHhaT03I3wReJDzMxdXMEOHdaZfY/FqmfKozea22aO8Pbx2v/tAno8/T/QhubRRaEAUGAAoUtAe8pA0=
  - secure: MSk9aG3EeEjFlfbrxarC2YK4rJyzKNbfCJjEWE7GCbL7SjoBPMFx9X1UK/8s71R713XobDSSFEBTZqZP7QYt0/XzAE26s72PxXl69YjJtcUJX2nECgPQBol59x0fsChlFhyd7baJIBkLV1ydHJT5nHGOnHDQogCqipa8N0A307Qo/j45c5MnvrejYqHNp4oI7sHtitPuCt3Ya8Vm3663WLW8qvwfKYpAdv7dkrcXQEk6tSU+14WZa01ZM8jk7qKNnW9vlTWj5PKAcLBjgXsFr05hYhEe6zgRtpLJo9uaqU+03XMEuiQeHtwAJw2lutOsaQI8WA2moiiGOLbvo3lvcLeunTmcVkAiTGnuCdtXsFncyUx23YBWM1qFSGwOVNNiZJAU+RSQAf+Fgpu1uUjprQHHjPeWEipas1CLY+Ii1D/m3gyPu9sNKw9rQ8aBFqsiXz8kj0Xow/Z2TyjzqtF5fUq5c9eoL7VAih7QwjafxFphipsmfL1y88I+MVT+W2HYzs7cPwlytg/CZBp25qtJoHJffINaLO/5es3zUzhZxi4A+d6rCw7luIPEzG4mXBH7FqtcKzoOJJMo6oXs1/ECA8cpgY10OTU9GezEMBhv1dsZ+Wl3mWGyxcr1IAz7dzg9FaZiXXUpGrRrl0gZoqy7TpwnXWFUSIzSAhmBLczw+cs=

before_install:
  - nvm install
  - nvm use
install: skip
script: make

before_deploy: cd browser-plugin && npm run sign
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ReEx1Fyk8Z/65H0B2cSp6rumxnpBUnZWNz4OSGWhwSYRQdxCwJByaURmmo6xIJn+kKbc58gRsA8YQ50ssYbkTozNWGKboz+tFV73G0KsrsxDtTKzKeS7h/GpJ6qo+4mjWmPpWPo5wkLj1vYjyKuStlRo7sXAluQvbQt3MCYx7NGGaONkyTASuR4Tx+atbs7NtPvBMtl3z4wa3tRS//x9OUX/kyHZkqEcffXIirple9q6VGErRly/VdY1W3VziHbaJG/Z6i9zZbTB6oWZe8GfKKFoiuq2szngnTToEeFn8oYHrV3/B26isVcGJdwfIfAnRrJXUZ7XOzXePR/xkFqfZMEPQfULQyKG+X6OGb/wOxjwGp/6mL3cKFZlUwqiGn9z3/A2BxwcxQgVkNWRsE5dTnZgThIksxVKaqFgL/6YC5uUZ/HnwGnYCT54eoqVnUsamPh7BMjncDZcIN+q3zZPU2EjDZ7CNoddg8bBV1ieiqdBpwD5D0EcCAwk7dib7CvBNTp2poB8j2wBIj1HY5TEuEppcXzJzOp3OGSpfx5UOgwQZkSkM/aY4U/g9RC/uVDmZfAyzSslKT6a6NlAhTdidEO/V2zKrLI+RTcJCpgXHxmoM06FVTjes0MPnaR6vmBR0LZ8lc4qO7MTTSlR35u6f7zmb3bIwF77qvTbxH/mlqs=
  file:
    - browser-plugin/build/package-unsigned.zip
    - browser-plugin/web-ext-artifacts/*.xpi
    - client/build/release.js
    - client/build/release.js.map
  draft: true
  on:
    tags: true
    repo: agiledigital/mule-preview
