language: clojure
dist: bionic

before_install:
  - nvm install
  - nvm use

install: skip

script: make -j2 -O

deploy:
  provider: releases
  api_key:
    secure: r7uHcpZB2iSKJFQUiJWiz9bhyZX+BLFa8EjLeVKyqosCADuCkSSYGhQAMlk7a+P00Y2g+ej1e/0KyI8oNm2ekwRN6SOHs4cLyriQBz7VlITIBVMwgrUIE+GfjdzmfxFnl+5w9bZMDxmeA7DXvJVLk0Yqq7TZV9K4j8p+wwdBxe1YMnn6UnaOkRC4TpEunpaKAlurqHCl6DTa+eEYzJfeaHL7+LHt2zqNOFZVyDFMtd5SPXWnIslsuo0F/9/ysILJI/ywmT3oW2ZYOpUEVJoQEEpXEoXd0DCw1p3buf2T2Se6Vdpk402apIPDIMeTXqJA9exozD4by/xlBdt1XgmDCcfTT+XNjtZlB3TzwKFMElPW5LkBpVtGNM2McA4hYA+OTeT5djz1In/UDduSkTMrP4nXzDEWqIM2Bw/uGb7WN20cgjDbG4OOfaRNe8m76r9hfLpqBK0fkgEYiTxMTz3bpUX7FaCsVV539/3eWBEkvkC6uZEfpaKdwujg//nFjE+ZptVjepZ4VDD/S8jsQh7g1/y7kCnv48uuVPKl4au4fC8HsqPGJF/bPJi02pQALnMolzyN1vzrPf9kw7q9DSFflau6p46eIyPz3anWhAOvPpFvRzsax29YY0A/PsEeNEkx0D8PUcUZnhC7qWqm/eoAm6LLXfSQc5fJAJShC+r1uMc=
  file:
    - browser-plugin/build/package.zip
    - client/build/release.js
    - client/build/release.js.map
  draft: true
  on:
    branch: master
    repo: agiledigital/mule-preview
