language: clojure
dist: bionic
env:
  global:
  - secure: dYQXYqrRFXFwKL79dssrtnBWyRtZqa6n86z9THAzl27ISZx9EL3ZjwwMIzNac0zrDWsaz3qs0EucshZGgvMQotvlQH5VwlRAKYff2L+4HnlY7cbH7zWwLgXWOa+ZtdlAef+/4Oi5xMkKpjzPydsUdQZf3wongJqTT8VTu0LG/bD/LWcsm7P5/2eRr/3vzVMF9keT4qhbBnNnCswY/UgTn/X2O+LmH/2hT0GZCy03hi/sz1lRb6+Vbvxm3ugG1CDJ4rrLHL4l+O6FkoaAR2sTRzJqWiKDShjzTuEgQDXn/n1dF+kwgurl99fzd9uPsmhQ1KjcvVtee9v3mEbyfWimi+6lncIy5XbYX/G8B5vwHLye8ijBF8OAXdeWZ+6lZAM41prsw2qM7qSWTg/J3V4X3N2L1521zsxFRC8II9xg+Zou0y9zHt1XKkXfXuZBoa/O0rGdxc1yfgbmrtw3gADeVT3uJe1iu3iv9hxrhp7XfbLCBfCKd2b40F9er/QRfo6LPfoNl28fBI9T003eQ1K7gj1b5vPi1V+447jVIA6yMaBBld9+/RIFUjtbyeTv5H5MIU2IuFED46h+oVLVwj2nE/IOYTVAUqlwQuBg3dRVm79ClwhzLN6YoBILQ4o2/aBNrIrs+hQb7PwyvWpO8kFvT5AuShbafDMMo4fVN/KdYmI=
  - secure: WVyxEonUYuYctSFYTjhGswrOp8WmBo9bO6Vs6e8N+qciut3nw+DNwc6pjQPP593NOPHZCFh6w2NW6oYYpcz1nnXN4TmkK9xebDFFCkf9h+zwkeYIK3hgDXLDYXic2jPydPB/mWaX8GaJOiTPFJUDEhnaHqojma1aw+ugLhzUkQZvEcdmauhaFejHQ2/NHMTEIbYRa0sgVTMo1JjKmXpQX6dOrwWEHIC4tGZrbaSvNz46ORyiXfc1BWG/k66p1rwvt0E1TfxaTbKzX+5i0hUnC1l0GOl4R8zD8wsySH8rd7HS1RDe0/04x9vPP5ZNHtr12vkoXAU33DbPEnK/ERlr2m3UYYcqq3VNFUEzccJKHE7+Ib8Emq2Ajsw+ItA166MGhaqcUOW+YrslAJjEPhkysoTQkVRrCh5fgEFY5JlK2+y4BNaE2okOrguJVG3Jj0fBump0YoKqHA0K8lRy7Y1zAdCj5JTwz0+nqE0TKFBMklvNR1xpuyDcltDeDwFEwB6b5IAo7Uj4DfHUBd7SE2Bc2qw42j/Jh2Sa3VyNYFIl2393eDdDOLRwR2LEAUEj1i8/6P8enAdeTplUc6cuGwlePswOgF6Axr9K/fQXUhhZEcoRe07hFtRe9dB6TiXrFWnUGWiWn8CTKHspcw343X9X9fLT6IE0xSwc1mVCr6JM8hM=
before_install:
- nvm install
- nvm use
install: skip
script: make
before_deploy: cd browser-plugin && npm run sign
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ReEx1Fyk8Z/65H0B2cSp6rumxnpBUnZWNz4OSGWhwSYRQdxCwJByaURmmo6xIJn+kKbc58gRsA8YQ50ssYbkTozNWGKboz+tFV73G0KsrsxDtTKzKeS7h/GpJ6qo+4mjWmPpWPo5wkLj1vYjyKuStlRo7sXAluQvbQt3MCYx7NGGaONkyTASuR4Tx+atbs7NtPvBMtl3z4wa3tRS//x9OUX/kyHZkqEcffXIirple9q6VGErRly/VdY1W3VziHbaJG/Z6i9zZbTB6oWZe8GfKKFoiuq2szngnTToEeFn8oYHrV3/B26isVcGJdwfIfAnRrJXUZ7XOzXePR/xkFqfZMEPQfULQyKG+X6OGb/wOxjwGp/6mL3cKFZlUwqiGn9z3/A2BxwcxQgVkNWRsE5dTnZgThIksxVKaqFgL/6YC5uUZ/HnwGnYCT54eoqVnUsamPh7BMjncDZcIN+q3zZPU2EjDZ7CNoddg8bBV1ieiqdBpwD5D0EcCAwk7dib7CvBNTp2poB8j2wBIj1HY5TEuEppcXzJzOp3OGSpfx5UOgwQZkSkM/aY4U/g9RC/uVDmZfAyzSslKT6a6NlAhTdidEO/V2zKrLI+RTcJCpgXHxmoM06FVTjes0MPnaR6vmBR0LZ8lc4qO7MTTSlR35u6f7zmb3bIwF77qvTbxH/mlqs=
  file:
  - browser-plugin/build/package-unsigned.zip
  - browser-plugin/web-ext-artifacts/*.xpi
  - client/build/release.js
  - client/build/release.js.map
  draft: true
  on:
    tags: true
    repo: agiledigital/mule-preview
